version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  run-test:  
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: chmod gradle permissions
          command: |
            chmod +x ./gradlew 

      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test 

      # Run UI Tests
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedFreeDebugAndroidTest connectedProDebugAndroidTest
          system-image: system-images;android-29;google_apis;x86
          post-emulator-launch-assemble-command: ./gradlew assembleFreeDebugAndroidTest
          max-tries: 1
  
  build-and-upload-debug-version:
    executor:
      name: android/android-machine
    
    steps:
      - run:
          name: Build and Upload Free Debug
          command: |
            ./gradlew assembleFreeDebug appDistributionUploadFreeDebug
      # save artifact

  build-and-upload-release-version:
    executor:
      name: android/android-machine
    
    steps:
      - run:
          name: Build and Upload Free Release
          command: |
            ./gradlew bundleFreeRelease appDistributionUploadFreeRelease
      # save artifact

# References:
# circleCI android command list: https://circleci.com/developer/orbs/orb/circleci/android
# circleCI android example: https://circleci.com/blog/building-android-on-circleci/
# firebase app-distribution: https://firebase.google.com/docs/app-distribution/android/distribute-gradle?authuser=0&apptype=aab

workflows:
  android-build-and-test:
    jobs:
      - run-test
      - build-and-upload-debug-version:
        filters:
          branches:
            only:
              - master
              - develop
      - build-and-upload-release-version:
        filters:
          branches:
            only:
              - master
              - develop