version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:  
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: chmod gradle permissions
          command: |
            chmod +x ./gradlew 

      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test 

      # - android/create-avd:
      #     avd-name: myavd
      #     install: true
      #     system-image: system-images;android-29;default;x86

      # - android/start-emulator:
      #     avd-name: myavd
      #     no-window: true
      #     restore-gradle-cache-prefix: v1a
          
      # - run:
      #     name: Run UI Tests
      #     command: |
      #       ./gradlew connectedAndroidTest 

      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedAndroidTest
          system-image: system-images;android-29;google_apis;x86
          post-emulator-launch-assemble-command: ./gradlew assembleFreeDebugAndroidTest	

      # TODO: build debug apk/aab then upload to firebase and save into artifact
      # - run:
          # name: Assemble Debug build
          # command: |
          # ./gradlew assembleDebug    

      # TODO: build release apk/aab
      # - run:
          # name: Assemble release build
          # command: |
          # ./gradlew assembleRelease    
          
      # TODO: sign release apk/aab then upload to firebase and save into artifact
      # - run:
          # name: Assemble release build
          # command: |
          # ./gradlew assembleRelease    

workflows:
  android-build-and-test:
    jobs:
      - build-and-test
