version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:  
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: chmod gradle permissions
          command: |
            chmod +x ./gradlew 

      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test 

      # Run UI Tests
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedFreeDebugAndroidTest connectedProDebugAndroidTest
          system-image: system-images;android-29;google_apis;x86
          post-emulator-launch-assemble-command: ./gradlew assembleFreeDebugAndroidTest
          max-tries: 1

# References:
# circleCI android command list: https://circleci.com/developer/orbs/orb/circleci/android
# circleCI android example: https://circleci.com/blog/building-android-on-circleci/
# firebase app-distribution: https://firebase.google.com/docs/app-distribution/android/distribute-gradle?authuser=0&apptype=aab


      # TODO: build debug apk/aab then upload to firebase and save into artifact
      # - run:
          # name: Assemble Debug build
          # command: |
          # ./gradlew assembleDebug    

      # TODO: build release apk/aab
      # - run:
          # name: Assemble release build
          # command: |
          # ./gradlew assembleRelease    
          
      # TODO: sign release apk/aab then upload to firebase and save into artifact
      # - run:
          # name: Assemble release build
          # command: |
          # ./gradlew assembleRelease    

workflows:
  android-build-and-test:
    jobs:
      - build-and-test
