version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:  
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: chmod gradle permissions
          command: |
            chmod +x ./gradlew 

      - run:
          name: Run Unit Test
          command: |
            ./gradlew test 

      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedAndroidTest
          system-image: system-images;android-29;google_apis;x86

      # TODO: build debug apk/aab then upload to firebase and save into artifact
      # - run:
          # name: Assemble Debug build
          # command: |
          # ./gradlew assembleDebug    

      # TODO: build release apk/aab
      # - run:
          # name: Assemble release build
          # command: |
          # ./gradlew assembleRelease    
          
      # TODO: sign release apk/aab then upload to firebase and save into artifact
      # - run:
          # name: Assemble release build
          # command: |
          # ./gradlew assembleRelease    

workflows:
  sample: 
    jobs:
      - build-and-test
