version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  setup-and-run-test:  
    executor:
      name: android/android-machine
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: chmod gradle permissions
          command: |
            chmod +x ./gradlew 
      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test 
      # Run UI Tests
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedFreeDebugAndroidTest connectedProDebugAndroidTest
          system-image: system-images;android-29;google_apis;x86
          post-emulator-launch-assemble-command: ./gradlew assembleFreeDebugAndroidTest
          max-tries: 1
      
      # TODO:
      # - persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - project
  
  build-and-upload-debug-version:
    executor:
      name: android/android-machine
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: chmod gradle permissions
          command: |
            chmod +x ./gradlew 
      - run:
          name: Build and Upload Free Debug
          command: |
            ./gradlew assembleFreeDebug appDistributionUploadFreeDebug
      - store_artifacts:
          path: app/build/outputs/apk/free/debug

  build-and-upload-release-version:
    executor:
      name: android/android-machine
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: chmod gradle permissions
          command: |
            chmod +x ./gradlew 
      # use sh .circleci/gen_key_store_and_properties.sh instead
      - run:
          name: generate keystore.properties
          command: |
            touch $KEY_PROPERTIES
            echo keyAlias = $KEY_ALIAS > $KEY_PROPERTIES
            echo keyPassword = $KEY_PASSWORD >> $KEY_PROPERTIES
            echo storeFile = $STORE_FILE >> $KEY_PROPERTIES
            echo storePassword = $STORE_PASSWORD >> $KEY_PROPERTIES
          environment:
            KEY_PROPERTIES: keystore.properties
      # use sh .circleci/gen_key_store_and_properties.sh instead
      - run:
          name: generate jks
          command: |
            echo $ACCOUNTING_KEYSTORE_BASE64 | base64 -d > ../accounting.jks
      - run:
          name: Build and Upload Free Release
          command: |
            ./gradlew assembleFreeRelease appDistributionUploadFreeRelease
          # ./gradlew bundleFreeRelease appDistributionUploadFreeRelease
      - store_artifacts:
          path: app/build/outputs/apk/free/release
        # path: app/build/outputs/bundle/freeRelease

# References:
# circleCI android command list: https://circleci.com/developer/orbs/orb/circleci/android
# circleCI android example: https://circleci.com/blog/building-android-on-circleci/
# firebase app-distribution: https://firebase.google.com/docs/app-distribution/android/distribute-gradle?authuser=0&apptype=aab

workflows:
  android-build-and-test:
    jobs:
      - setup-and-run-test
      - build-and-upload-debug-version:
          requires: 
            - setup-and-run-test
          filters:
            branches:
              only:
                - develop
      - build-and-upload-release-version:
          requires: 
            - setup-and-run-test
          filters:
            branches:
              only:
                - master